CREATE TABLE ORDER_ITEM(
    ITEM_ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT VARCHAR(20) NOT NULL,
    AMOUNT INT NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDER_ENTITY(ORDER_ID)
);